=== playlogo/featureFlags/features/utils/feature.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "type": {
            "type": "string"
        },
        "executable": {
            "type": "string"
        },
        "websocket": {
            "type": "boolean"
        },
        "args": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "expose": {
            "type": "object",
            "properties": {
                "inline": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "param": {
                                "type": "string"
                            },
                            "type": {
                                "type": "string",
                                "enum": [
                                    "string",
                                    "number",
                                    "boolean",
                                    "array"
                                ]
                            },
                            "description": {
                                "type": "string"
                            },
                            "default": {
                                "oneOf": [
                                    {
                                        "type": "string"
                                    },
                                    {
                                        "type": "number"
                                    },
                                    {
                                        "type": "array"
                                    }
                                ]
                            },
                            "specific": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "name",
                            "param",
                            "type",
                            "description",
                            "default"
                        ]
                    }
                }
            },
            "required": [
                "inline"
            ]
        },
        "report": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "descriptions": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "type",
                    "descriptions"
                ]
            }
        }
    },
    "required": [
        "type",
        "executable",
        "websocket",
        "args",
        "expose"
    ]
}

=== playlogo/featureFlags/features/volume/feature.json
{
    "type": "process",
    "executable": "deno",
    "args": [
        "main.ts"
    ],
    "websocket": true,
    "expose": {
        "inline": [
            {
                "name": "volume",
                "param": "--volume",
                "type": "number",
                "description": "Initial volume, must be in range 0 - 100",
                "default": 50,
                "specific": "volume"
            }
        ]
    }
}
